### ISSUE TITLE
Backup to object storage via VPE

### ISSUE THREAD

**Issue by phoneline99** [ibm-cloud-docs/power-iaas#66]
Should an option to use a VPE in VPC instead of proxy via Classic be listed as an option.

**Comment by smatzek** [comment]
In particular, this page, https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-backup-strategies should be heavily updated discuss the use of IBM Cloud Object Storage VPEs instead of reverse proxies for the COS access.

**Comment by smatzek** [comment]
The backup strategies topic should be updated for PER and VPE support for connecting to Cloud Object Storage.

In short, the preferred way to connect to Cloud Object Storage (COS) from a VSI in Power System Virtual Server should be these options in preference order:

1. In PER enabled workspaces, you should simply be able to attach the Power System Virtual Server workspace to a transit gateway as documented here, https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-per#attaching-transit-gateway-to-a-per-workspace, and directly access the COS direct endpoint. I haven't tested this yet since PER just came out.

2. In non-PER enabled workspaces that are in a multi-zone region (MZR) the best way to connect to Cloud Object storage is to create a Virtual Private Cloud with subnet(s) in the same region as your Power Virtual Server workspace and then create a virtual private pndpoint Gateway (VPE): https://cloud.ibm.com/docs/vpc?topic=vpc-about-vpe. The VPC should be connected to a transit gateway and the Power Virtual Server should be connected to a transit gateway with cloud connections. The Power virtual servers would then use the VPE's IP address to connect to COS. If the VPE has multiple IP addresses, custom DNS can be set up and the custom hostname can be used to connect to COS.

3. Use a Nginx reverse proxy server in either VPC or Classic as currently documented.

Given the above, the IBM i backup strategies here: https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-backup-strategies#backup-ibmi should be changed to document option 2 above since PER is only in one zone.

The "Using Cloud Object Storage over IBM Cloud Direct Link" section, https://cloud.ibm.com/docs/power-iaas?topic=power-iaas-backup-strategies#cos-over-directlink, should also change to use option 2 and remove references to a proxy server.

**Comment by Itsmemukesh** [comment]
Added the changes and pushed in the test: https://test.cloud.ibm.com/docs/power-iaas?topic=power-iaas-backup-strategies#cos-over-directlink
Let me know if you want any further changes.

**Comment by Itsmemukesh** [comment]
Additional changes are done in IBM i section.

**Comment by smatzek** [comment]
The changes look good, this issue looks completely addressed.
Thanks!
