### ISSUE TITLE
can we add details on how to copy the mksysb image to this server?

### ISSUE THREAD

**Issue by bikasprice** [ibm-cloud-docs/power-iaas#7]
Details of how to use ICOS would be helpful.  we can either include this as a standalone topic, and reference it.  Or add it to this section.
Contents should something like the following:

[Using ICOS with Power VS.docx](https://github.com/ibm-cloud-docs/power-iaas/files/3786457/Using.ICOS.with.Power.VS.docx)

if you have questions on any of this please reach out to me - charles_price@us.ibm.com

**Comment by mpbagwel** [comment]
Sure, not a problem. I added a callout on downloading the image using the IBM Cloud console and CLI. For your awareness, IBM Cloud docs does not pull in instructional content from our competitors due to legal reasons. I won't be able to include any of AWS information in our documentation as a result. We also try to avoid duplicating content that has already been documented elsewhere unless it is absolutely critical. 

>If you'd like to download your image at a later point, go to the **Resource List** in the IBM Cloud console. Once there, access your Cloud Object Storage service instance. In the bucket where your image is stored, select the image file that you want to download and select **Download objects**. See [Download an object](/docs/services/cloud-object-storage?topic=cloud-object-storage-ic-use-the-ibm-cli) for the Cloud Object Storage CLI command.
